service: creator
provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: eu-west-2
  memorySize: 2048
  timeout: 180
functions:
  app:
    handler: lambda.universal
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
